# Generated by Django 5.0.3 on 2024-03-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_transaction_from_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'EUR')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(choices=[('T', 'Transfer'), ('BD', 'Bank Deposit'), ('BW', 'Withdraw to Bank'), ('WM', 'Withdraw to mobile wallet'), ('MD', 'Merchant Deposit'), ('MW', 'Merchant withdraw'), ('MD', 'Mobile wallet deposit')], max_length=100),
        ),
    ]
