# Generated by Django 5.0.3 on 2024-03-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240311_1300'),
    ]

    operations = [
    ]
