# Generated by Django 5.0.3 on 2024-03-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240311_1308'),
    ]

    operations = [
    ]
