# Generated by Django 5.0.3 on 2024-03-12 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appuser_category_transaction_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='created_at',
            new_name='date_joined',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Kyc_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_passport_front', models.CharField(max_length=200, null=True)),
                ('id_passport_back', models.CharField(max_length=200, null=True)),
                ('id_passport_number', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appuser')),
            ],
        ),
    ]
