# Generated by Django 5.0.3 on 2024-03-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_created_at_appuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
